import { UsersPaginationModel } from '../types'

/* eslint-disable max-lines */
export const exampleUsersPaginationModel: UsersPaginationModel = {
  pagination: {
    page: 1,
    pageSize: 8,
    pagesCount: 3,
    totalCount: 50,
  },
  users: [
    {
      createdAt: new Date('2023-01-01T00:00:00Z'),
      email: 'user1@example.com',
      id: 1,
      profile: {
        aboutMe: 'Hello, I am User 1.',
        avatars: [],
        city: 'Moscow',
        country: 'Russia',
        createdAt: new Date('2023-01-01T00:00:00Z'),
        dateOfBirth: new Date('1990-01-01T00:00:00Z'),
        firstName: 'Ivan',
        id: 1,
        lastName: 'Ivanov',
        region: 'Central',
        userName: 'ivan_1',
      },
      userBan: null,
      userName: 'ivan1',
    },
    {
      createdAt: new Date('2023-01-02T00:00:00Z'),
      email: 'user2@example.com',
      id: 2,
      profile: {
        aboutMe: 'Hello, I am User 2.',
        avatars: [],
        city: 'Saint Petersburg',
        country: 'Russia',
        createdAt: new Date('2023-01-02T00:00:00Z'),
        dateOfBirth: new Date('1992-02-02T00:00:00Z'),
        firstName: 'Anna',
        id: 2,
        lastName: 'Petrova',
        region: 'Northwest',
        userName: 'anna_2',
      },
      userBan: {
        createdAt: new Date('2023-02-01T00:00:00Z'),
        reason: 'Violation of community guidelines',
      },
      userName: 'anna2',
    },
    {
      createdAt: new Date('2023-01-03T00:00:00Z'),
      email: 'user3@example.com',
      id: 3,
      profile: {
        aboutMe: 'Hello, I am User 3.',
        avatars: [],
        city: 'Kazan',
        country: 'Russia',
        createdAt: new Date('2023-01-03T00:00:00Z'),
        dateOfBirth: new Date('1988-03-15T00:00:00Z'),
        firstName: 'Dmitry',
        id: 3,
        lastName: 'Sokolov',
        region: 'Volga',
        userName: 'dmitry_3',
      },
      userBan: null,
      userName: 'dmitry3',
    },
    {
      createdAt: new Date('2023-01-04T00:00:00Z'),
      email: 'user4@example.com',
      id: 4,
      profile: {
        aboutMe: 'Hello, I am User 4.',
        avatars: [],
        city: 'Novosibirsk',
        country: 'Russia',
        createdAt: new Date('2023-01-04T00:00:00Z'),
        dateOfBirth: new Date('1995-06-20T00:00:00Z'),
        firstName: 'Olga',
        id: 4,
        lastName: 'Ivanova',
        region: 'Siberian',
        userName: 'olga_4',
      },
      userBan: null,
      userName: 'olga4',
    },
    {
      createdAt: new Date('2023-01-05T00:00:00Z'),
      email: 'user5@example.com',
      id: 5,
      profile: {
        aboutMe: 'Hello, I am User 5.',
        avatars: [],
        city: 'Yekaterinburg',
        country: 'Russia',
        createdAt: new Date('2023-01-05T00:00:00Z'),
        dateOfBirth: new Date('1993-11-11T00:00:00Z'),
        firstName: 'Alexey',
        id: 5,
        lastName: 'Petrov',
        region: 'Ural',
        userName: 'alexey_5',
      },
      userBan: null,
      userName: 'alexey5',
    },
    {
      createdAt: new Date('2023-01-06T00:00:00Z'),
      email: 'user6@example.com',
      id: 6,
      profile: {
        aboutMe: 'Hello, I am User 6.',
        avatars: [],
        city: 'Nizhny Novgorod',
        country: 'Russia',
        createdAt: new Date('2023-01-06T00:00:00Z'),
        dateOfBirth: new Date('1985-04-25T00:00:00Z'),
        firstName: 'Maria',
        id: 6,
        lastName: 'Smirnova',
        region: 'Volga',
        userName: 'maria_6',
      },
      userBan: {
        createdAt: new Date('2023-03-01T00:00:00Z'),
        reason: 'Spam',
      },
      userName: 'maria6',
    },
    {
      createdAt: new Date('2023-01-07T00:00:00Z'),
      email: 'user7@example.com',
      id: 7,
      profile: {
        aboutMe: 'Hello, I am User 7.',
        avatars: [],
        city: 'Chelyabinsk',
        country: 'Russia',
        createdAt: new Date('2023-01-07T00:00:00Z'),
        dateOfBirth: new Date('1990-08-30T00:00:00Z'),
        firstName: 'Sergey',
        id: 7,
        lastName: 'Kuznetsov',
        region: 'Ural',
        userName: 'sergey_7',
      },
      userBan: null,
      userName: 'sergey7',
    },
    {
      createdAt: new Date('2023-01-08T00:00:00Z'),
      email: 'user8@example.com',
      id: 8,
      profile: {
        aboutMe: 'Hello, I am User 8.',
        avatars: [],
        city: 'Voronezh',
        country: 'Russia',
        createdAt: new Date('2023-01-08T00:00:00Z'),
        dateOfBirth: new Date('1989-12-12T00:00:00Z'),
        firstName: 'Tatiana',
        id: 8,
        lastName: 'Fedorova',
        region: 'Central',
        userName: 'tatiana_8',
      },
      userBan: null,
      userName: 'tatiana8',
    },
    {
      createdAt: new Date('2023-01-09T00:00:00Z'),
      email: 'user9@example.com',
      id: 9,
      profile: {
        aboutMe: 'Hello, I am User 9.',
        avatars: [],
        city: 'Rostov-on-Don',
        country: 'Russia',
        createdAt: new Date('2023-01-09T00:00:00Z'),
        dateOfBirth: new Date('1991-05-05T00:00:00Z'),
        firstName: 'Andrey',
        id: 9,
        lastName: 'Novikov',
        region: 'Southern',
        userName: 'andrey_9',
      },
      userBan: null,
      userName: 'andrey9',
    },
    {
      createdAt: new Date('2023-01-10T00:00:00Z'),
      email: 'user10@example.com',
      id: 10,
      profile: {
        aboutMe: 'Hello, I am User 10.',
        avatars: [],
        city: 'Samara',
        country: 'Russia',
        createdAt: new Date('2023-01-10T00:00:00Z'),
        dateOfBirth: new Date('1987-07-07T00:00:00Z'),
        firstName: 'Elena',
        id: 10,
        lastName: 'Vasilieva',
        region: 'Volga',
        userName: 'elena_10',
      },
      userBan: null,
      userName: 'elena10',
    },
    {
      createdAt: new Date('2023-01-11T00:00:00Z'),
      email: 'user11@example.com',
      id: 11,
      profile: {
        aboutMe: 'Hello, I am User 11.',
        avatars: [],
        city: 'Krasnodar',
        country: 'Russia',
        createdAt: new Date('2023-01-11T00:00:00Z'),
        dateOfBirth: new Date('1994-02-14T00:00:00Z'),
        firstName: 'Victor',
        id: 11,
        lastName: 'Stepanov',
        region: 'Southern',
        userName: 'victor_11',
      },
      userBan: null,
      userName: 'victor11',
    },
    {
      createdAt: new Date('2023-01-12T00:00:00Z'),
      email: 'user12@example.com',
      id: 12,
      profile: {
        aboutMe: 'Hello, I am User 12.',
        avatars: [],
        city: 'Vladivostok',
        country: 'Russia',
        createdAt: new Date('2023-01-12T00:00:00Z'),
        dateOfBirth: new Date('1996-03-22T00:00:00Z'),
        firstName: 'Svetlana',
        id: 12,
        lastName: 'Morozova',
        region: 'Far East',
        userName: 'svetlana_12',
      },
      userBan: null,
      userName: 'svetlana12',
    },
    {
      createdAt: new Date('2023-01-13T00:00:00Z'),
      email: 'user13@example.com',
      id: 13,
      profile: {
        aboutMe: 'Hello, I am User 13.',
        avatars: [],
        city: 'Tyumen',
        country: 'Russia',
        createdAt: new Date('2023-01-13T00:00:00Z'),
        dateOfBirth: new Date('1982-09-09T00:00:00Z'),
        firstName: 'Igor',
        id: 13,
        lastName: 'Petrovich',
        region: 'Siberian',
        userName: 'igor_13',
      },
      userBan: {
        createdAt: new Date('2023-04-01T00:00:00Z'),
        reason: 'Inappropriate content',
      },
      userName: 'igor13',
    },
    {
      createdAt: new Date('2023-01-14T00:00:00Z'),
      email: 'user14@example.com',
      id: 14,
      profile: {
        aboutMe: 'Hello, I am User 14.',
        avatars: [],
        city: 'Khabarovsk',
        country: 'Russia',
        createdAt: new Date('2023-01-14T00:00:00Z'),
        dateOfBirth: new Date('1993-10-10T00:00:00Z'),
        firstName: 'Natalia',
        id: 14,
        lastName: 'Borisova',
        region: 'Far East',
        userName: 'natalia_14',
      },
      userBan: null,
      userName: 'natalia14',
    },
    {
      createdAt: new Date('2023-01-15T00:00:00Z'),
      email: 'user15@example.com',
      id: 15,
      profile: {
        aboutMe: 'Hello, I am User 15.',
        avatars: [],
        city: 'Ufa',
        country: 'Russia',
        createdAt: new Date('2023-01-15T00:00:00Z'),
        dateOfBirth: new Date('1988-12-12T00:00:00Z'),
        firstName: 'Mikhail',
        id: 15,
        lastName: 'Semyonov',
        region: 'Bashkortostan',
        userName: 'mikhail_15',
      },
      userBan: null,
      userName: 'mikhail15',
    },
    {
      createdAt: new Date('2023-01-16T00:00:00Z'),
      email: 'user16@example.com',
      id: 16,
      profile: {
        aboutMe: 'Hello, I am User 16.',
        avatars: [],
        city: 'Saratov',
        country: 'Russia',
        createdAt: new Date('2023-01-16T00:00:00Z'),
        dateOfBirth: new Date('1991-11-11T00:00:00Z'),
        firstName: 'Olga',
        id: 16,
        lastName: 'Dmitrieva',
        region: 'Volga',
        userName: 'olga_16',
      },
      userBan: null,
      userName: 'olga16',
    },
    {
      createdAt: new Date('2023-01-17T00:00:00Z'),
      email: 'user17@example.com',
      id: 17,
      profile: {
        aboutMe: 'Hello, I am User 17.',
        avatars: [],
        city: 'Kostroma',
        country: 'Russia',
        createdAt: new Date('2023-01-17T00:00:00Z'),
        dateOfBirth: new Date('1989-05-25T00:00:00Z'),
        firstName: 'Vladimir',
        id: 17,
        lastName: 'Ivanovich',
        region: 'Central',
        userName: 'vladimir_17',
      },
      userBan: null,
      userName: 'vladimir17',
    },
    {
      createdAt: new Date('2023-01-18T00:00:00Z'),
      email: 'user18@example.com',
      id: 18,
      profile: {
        aboutMe: 'Hello, I am User 18.',
        avatars: [],
        city: 'Tver',
        country: 'Russia',
        createdAt: new Date('2023-01-18T00:00:00Z'),
        dateOfBirth: new Date('1992-01-01T00:00:00Z'),
        firstName: 'Elizaveta',
        id: 18,
        lastName: 'Kovaleva',
        region: 'Central',
        userName: 'elizaveta_18',
      },
      userBan: null,
      userName: 'elizaveta18',
    },
    {
      createdAt: new Date('2023-01-19T00:00:00Z'),
      email: 'user19@example.com',
      id: 19,
      profile: {
        aboutMe: 'Hello, I am User 19.',
        avatars: [],
        city: 'Kursk',
        country: 'Russia',
        createdAt: new Date('2023-01-19T00:00:00Z'),
        dateOfBirth: new Date('1994-07-07T00:00:00Z'),
        firstName: 'Artem',
        id: 19,
        lastName: 'Sokolov',
        region: 'Central',
        userName: 'artem_19',
      },
      userBan: null,
      userName: 'artem19',
    },
    {
      createdAt: new Date('2023-01-20T00:00:00Z'),
      email: 'user20@example.com',
      id: 20,
      profile: {
        aboutMe: 'Hello, I am User 20.',
        avatars: [],
        city: 'Nizhnekamsk',
        country: 'Russia',
        createdAt: new Date('2023-01-20T00:00:00Z'),
        dateOfBirth: new Date('1986-03-30T00:00:00Z'),
        firstName: 'Anastasia',
        id: 20,
        lastName: 'Petrova',
        region: 'Tatarstan',
        userName: 'anastasia_20',
      },
      userBan: null,
      userName: 'anastasia20',
    },
  ],
}
