export const AUTH_ERRORS = {
  EMAIL_INVALID_ERROR: 'emailInvalidError',
  EMAIL_REQUIRED_ERROR: 'emailRequiredError',
  EMAIL_TAKEN_ERROR: 'emailTakenError',
  PASSWORD_CONFIRMATION_INVALID_ERROR: 'passwordConfirmationInvalidError',
  PASSWORD_CONFIRMATION_REQUIRED_ERROR: 'passwordConfirmationRequiredError',
  PASSWORD_INVALID_ERROR: 'passwordInvalidError',
  PASSWORD_REQUIRED_ERROR: 'passwordRequiredError',
  PASSWORD_TOO_LONG_ERROR: 'passwordToLongError',
  PASSWORD_TOO_SHORT_ERROR: 'passwordToShortError',
  PRIVACY_POLICY_REQUIRED_ERROR: 'privacyPolicyRequiredError',
  USERNAME_REQUIRED_ERROR: 'usernameRequiredError',
  USERNAME_TAKEN_ERROR: 'usernameTakenError',
  USERNAME_TOO_LONG_ERROR: 'usernameTooLongError',
  USERNAME_TOO_SHORT_ERROR: 'usernameTooShortError',
} as const
